server {
    # <--- CAMBIO CLAVE: Puerto hardcodeado a 8080.
    listen 8080;
    server_name _;
    root /var/www/html/public;

    index index.php index.html;

    client_max_body_size 20M;

    # Ocultar la versión de Nginx por seguridad
    server_tokens off;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;

        # <--- CAMBIO CLAVE: Conexión a PHP por TCP, no por socket.
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_read_timeout 300;
    }

    # Prevenir el acceso a archivos ocultos
    location ~ /\.ht {
        deny all;
    }
}
